### PR TITLE
Simple version

### PR DESCRIPTION
**Pull request by Bloodninj**
Attempt at a simpler version that doesn't do the checking to see if something needs to be stored, before storing it.

### CODE REVIEW

**Comment by nanjizal** [comment]
I think you can remove this
```haxe    @:keep
    public function customSerialize(ctx : hxbit.Serializer) {
        bitLength = 1 << 2;
        // store bits that need adding.
        ctx.addInt( bitLength );
        ctx.addFloat( alpha );
        ctx.addInt( colorID );
        ctx.addInt( textureID );
    }
    inline public function add( mask: Int ){
            bitLength = bitLength | mask;
    }
    inline public static function contains( bits :Int, mask :Int ) :Bool{
            return bits & mask != 0;
    }
    @:keep
    public function customUnserialize(ctx : hxbit.Serializer) {
        bitLength = ctx.getInt();
        if( bitLength == 0 ) return;
        alpha       = ctx.getFloat();
        colorID     = ctx.getInt();
        textureID   = ctx.getInt();
    }
```

then add @s to properties your using remove rest

**Comment by nanjizal** [comment]
so these need removing or adding  @:s
```    
public var bitLength: Int = 0;
    public var alpha: Float = 1. ;
    public var colorID: Int = 0xFF000000;
    public var textureID: Int = -1; 
```

**Comment by nanjizal** [comment]
so perhaps just use colour and alpha

**Comment by Bloodninj** [comment]
I've left the `textureID` property in there but without `@:s`, since the normal code also sets a textureID in Main.hx. Seems to work?

**Comment by nanjizal** [comment]
The textureID won't get serialized, probably cleaner to remove it and remove it in main.  Also worth updating Readme.  Cheers for the input.  Let me know if you can just make these tweaks and I will accept.

**Comment by nanjizal** [comment]
I hope it's been useful in getting to grips with Serialization, if you get stuck with doing it in fixel let me know, better perhaps to serialize data more than fixel structures, and just use custom to rebuild when loading.

**Pull request merged**
